### PR TITLE
Meter/balance reset feature

### PR DESCRIPTION
**Pull request by stephenhu3**
Hi, I'm a big fan of this extension and use it frequently, but I always wished there was a reset charge and reset meter button when I'm feeling extra productive.

I haven't coded in JavaScript much, so I started learning it to contribute to this extension. Please let me know how my code can be improved. Thanks!

**Changes**
1. popup.html
   - added parent div ".add-meter" for the original buttons that add to meter
   - added parent divs ".dump-balance" and ".dump-meter" for my buttons that reset balance and meter, respectively
2. popup.js
   - added on click event for reset balance and reset meter buttons
   - original on click event for the buttons is targeted by ".add-meter" parent div class instead of "body"
3. background.js
   - added logic to avoid negative meter count after resetting meter
   - created a "public" caller for checkall() function by moving it under "monitor" window property so it can be called in popup.js after resetting meter (not quite sure if this was the proper approach for making a function accessible by another file)

### CODE REVIEW

**Comment by stephenhu3** [comment]
Found bug with implementation. Will investigate and fix. Closing pull request.

**Comment by tkazec** [comment]
Hi @stephenhu3, thanks for the contribution! I'm currently really busy with a work deadline but will be super happy to review this in a week or two. Let me know when you're ready!

**Comment by stephenhu3** [comment]
Hi @tkazec, I recently wrapped up my exams and got some time to dive in on this and fix the bugs I had.
* Dumping balance updates the count immediately (needed to call sync after deducting the balance)
* Dumping meter loads popup.html page accordingly for tabs on blocked sites (needed to call checkall)

Apologies for the wait, and thanks again for the extension. Please let me know how my code can be improved!

**Comment by stephenhu3** [comment]
Hi @tkazec,
Just revisiting this old PR. I've noticed "Balance reset button." was included in your list of ideas, and this PR implements this feature, as well as "Meter reset".
screenshot 2015-12-06 19 04 45

Cheers!
Stephen

**Comment by tkazec** [comment]
Hi again Stephen! So sorry for dropping off the map. Will take a look shortly!

**Comment by tkazec** [comment]
@stephenhu3 Can you turn this on so I can make some quick edits?^^ https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by stephenhu3** [comment]
Hi Teddy, thanks for revisiting this! I still use this extension daily.

This pull request can definitely be cleaned up, as it was an exploratory piece I made quite some time ago when I was first learning about front-end work.

I've enabled the setting. Cheers!

**Comment by tddyco** [comment]
@stephenhu3 I've just pushed v1.1.0 to the Chrome Web Store, which includes this PR! Thanks a lot for the help, and let me know what you think – ended up changing the design and implementation a bit, but can definitely improve it in the next release.

**Comment by stephenhu3** [comment]
Cheers! I've downloaded it from the Web Store and got to test it out. The refactor looks good and is definitely more organized than what I wrote the few years back.

My only feedback in future iterations may be to have the reset buttons for balance and meter to perhaps be more explicit to the user. The little X's made sense to me, but I noticed the "Balance" and "Meter" text itself is included in the reset button container, and clicking just the text triggers the reset, which I anticipate may cause some unintended resets among curious users.

I was initially imagining maybe moving the red reset block buttons to the top. But perhaps to keep the interface as minimal as possible without the additional block buttons, maybe a text change to "Reset Balance" and "Reset Meter" or a tool tip on mouseover would suffice.

Thanks for revisiting this!

**Comment by tddyco** [comment]
Yeah, I wanted to add tooltips, but the installed version of Bootstrap is so old that I decided to pass. When I upgrade Bootstrap I'll add them :)

**Pull request merged**
